### ISSUE TITLE
vacuum not available

### ISSUE THREAD

**Issue by msslava** [denysdovhan/vacuum-card#129]
**Before submitting a bug**

[ x] I updated to the latest version available
[x ] I cleared the cache of my browser

**Describe the bug**

```
Error while setting up xiaomi_miio platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 201, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 310, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 481, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 522, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 323, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/vacuum.py", line 339, in device_state_attributes
    if self.timers:
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/vacuum.py", line 284, in timers
    return [
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/vacuum.py", line 288, in <listcomp>
    "next_schedule": as_utc(timer.next_schedule),
AttributeError: 'Timer' object has no attribute 'next_schedule'
```

**Steps to reproduce**

Vacuum cleaner is not available.

**Expected behavior**

**Screenshots**
For example, JavaScript errors are shown in the web inspector (if applicable).

**Versions:**

- Release: [latest]
- Browser: [e.g. chrome, safari]
- HomeAssistant version: [0.116.2]

**Comment by krystiancharubin** [comment]
Looks like you are having an issue with the vacuum integration, not the card.

**Comment by krystiancharubin** [comment]
Looks like you are having an issue with the vacuum integration, not the card.
