### ISSUE TITLE
Card is not shown when device in "cleaning" state - Roborock integration

### ISSUE THREAD

**Issue by M1K3SD1** [denysdovhan/vacuum-card#526]
**Before submitting a bug**

[V ] I updated to the latest version available
[V ] I cleared the cache of my browser

**Describe the bug**

I have installed the new Roborock integration in HA - https://www.home-assistant.io/integrations/roborock
But seems the card is not fully supporting it since when the state is "cleaning" the card throws an error.
I am also submitting an issue for the integration since it doesn't seem to get any statistical attributes.

**Steps to reproduce**

1. Go to the UI, no card is shown when the vacuum is in cleaning state.
2. Check debug tools
3. See error

```Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'state')
    at vacuum-card.js:4:23314
    at Array.map (<anonymous>)
    at r.value (vacuum-card.js:4:23175)
    at r.value (vacuum-card.js:4:28901)
    at r.update (vacuum-card.js:1:26934)
    at r.performUpdate (vacuum-card.js:1:18184)
    at r.scheduleUpdate (vacuum-card.js:1:17835)
    at r._$E_ (vacuum-card.js:1:17743)```

**Expected behavior**
Card should show state: "cleaning"

**Screenshots**
If applicable, add screenshots to help explain your problem.
For example, JavaScript errors are shown in the web inspector (if applicable).

**Versions:**

- Release: v2.6.3
- Browser: Chrome
- HomeAssistant version: 2023.5.2

**Comment by denysdovhan** [comment]
Could you share how Roborock reports its states? Please go to Developer Tools > States > (Find your vacuum). Send your attributes and state. You can send a screenshot as well.

**Comment by Tamsy** [comment]
Without any means of hijacking this thread: The very same is also happening when device is in "cleaning" state when using the  Xiaomi Miio integration: 

![Roborock_01](https://github.com/denysdovhan/vacuum-card/assets/6210614/b857460a-ac62-4809-a46b-be959a0e42e2)

![Roborock_02](https://github.com/denysdovhan/vacuum-card/assets/6210614/83784402-cedb-4875-843c-3d0d7a499d22)




Additionally, defining the background color of the card seems not to function anymore:

```
type: custom:vacuum-card
style: |
  ha-card {
    --vc-background: #87CEEB;
  }
entity: vacuum.roborock_s5_max_unten
```
